Sprint 12
Depechist/ImageFeed pull request #6
Opened 2023-05-22 13:08 UTC by Depechist

2023-05-23 05:41 UTC, mmbabaev requested changes

2023-05-23 05:41 UTC, mmbabaev commented on ImageFeed/AppDelegate.swift
> +        ProgressHUD.animationType = .systemActivityIndicator
предлагаю настройку ProgressHUD тоже спрятать под нашу обертку в отдельный метод. Так мы отовсюду уберем зависимость на библиотеку

2023-05-23 05:41 UTC, mmbabaev commented on ImageFeed/Auth/WebViewViewController.swift
> +        // Очищаем все куки из хранилища
хорошо

2023-05-23 05:41 UTC, mmbabaev commented on ImageFeed/Helpers/URLRequest+Extensions.swift
> +    public func cURL(pretty: Bool = false) -> String {
это для проверки?

2023-05-23 05:41 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListService.swift
> +        for result in photoResult {
название не соответствует тому, что делает функция. 
Также можно лаконичнее написать:
```
photos.append(contentsOf: photoResult.map { $0.asPhoto() })

2023-05-25 11:38 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let dateFormatter = DateFormatter()
Сейчас хорошо сделано, используются два форматтера. Но лучше сами форматтеры создавать один раз, это дорогая операция. Здесь можно подробнее прочитать про это

2023-05-25 11:41 UTC, mmbabaev commented on ImageFeed/Profile/ProfileService.swift
> +        let name = ProfileResult.lastName != nil ? "\(ProfileResult.firstName) \(ProfileResult.lastName!)" : "\(ProfileResult.firstName)"
здесь получилось сложно и с форс анрапами. Можно записать это короче и безопаснее так: 
```
val lastName = profileResult.lastName.map { " \($0)" } ?? ""
let name = profileResult.firstName + lastName
```
Также аргументы функций принято называть с маленькой буквы.

2023-05-25 11:41 UTC, mmbabaev approved these changes

2023-05-25 12:22 UTC, Depechist commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let dateFormatter = DateFormatter()
Не совсем понимаю что от меня требуется сейчас.
Учебник предлагает сначала сделать так:

let createdAt = photoResult.createdAt // "2016-05-03T11:00:28-04:00"
let dateFormatter = ISO8601DateFormatter()
let date = dateFormatter.date(from: createdAt) 

И далее так:

let dateFormatter = DateFormatter()
dateFormatter.dateStyle = .medium
dateFormatter.timeStyle = .none
dateFormatter.string(from: date) // "3 May 2016" 

При этом оговаривая, что форматер **желательно** (но не обязательно) создать один раз.

Использовать только ISO8601DateFormatter() и свойства форматтера .dateStyle и .timeStyle невозможно, так как ISO8601DateFormatter() не имеет таких свойств. Xcode выдает соответствующую ошибку: "value of type 'ISO8601DateFormatter' has no member 'dateStyle'"

Немного изменил код. Теперь работа в форматтером в ImagesListViewController выглядит так:

на 16 строчке:

private lazy var dateFormatter: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        return formatter
    }()
    
    и на 85 строчке
    
    if let createdAt = image.createdAt, // "2016-05-03T11:00:28-04:00"
           let date = dateFormatter.date(from: createdAt) {
            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .medium
            dateFormatter.timeStyle = .none
            cell.dateLabel.text = dateFormatter.string(from: date) // "3 May 2016"
        } else {
            cell.dateLabel.text = "date error"
        }
        
        В таком варианте могу отправлять на ревью?

2023-05-26 19:57 UTC, mmbabaev approved these changes

2023-05-26 19:57 UTC, mmbabaev commented on ImageFeed/Profile/ProfileService.swift
> +//        let name = profileResult.lastName != nil ? "\(profileResult.firstName) \(profileResult.lastName!)" : "\(profileResult.firstName)"
не оставляйте закомментированный код в работе, которую вы сдаете на проверку

2023-05-26 19:57 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private lazy var dateFormatterIso: ISO8601DateFormatter = {
Можно просто
```
private lazy var dateFormatterIso = ISO8601DateFormatter()

2023-05-28 09:21 UTC, merged